spring:
  application:
    name: openAI
  ai:
    chat:
      client:
        enabled: true
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
server:
  port: 8000